### Exercise 1

Code from lecture 1.2 - 2.1

In [ ]:
# 1) Ask user to enter a number
n = int(input("Enter a number: "))

# 2) Check if the number is prime
if n <= 1:
    print("This is not a prime number")
else:
    is_prime = True

    for i in range(2, n):
        if n % i == 0:
            is_prime = False

    # 3) Print the result
    if is_prime:
        print("This is a prime number")
    else:
        print("This is not a prime number")

### Exercise 2

Code from lecture 2.1

In [ ]:
# Ask user how many Fibonacci numbers to display
n = int(input("How many Fibonacci numbers? "))

a = 0
b = 1

# Print Fibonacci sequence
for i in range(n):
    print(a, end=' ')
    next_num = a + b
    a = b
    b = next_num

### Exercise 3

Code from lecture 2.1 - Exercise 2

In [ ]:
n = 5

# top
for i in range(n, 0, -1):
    for j in range(i):
        print('*', end=' ')
    print()

# bottom
for i in range(2, n + 1):
    for j in range(i):
        print('*', end=' ')
    print()

### Exercise 4

Code from lecture 2.1

In [ ]:
# Define the function
def reverse_text():
    text = input("Enter a string: ")
    
    reversed_text = ""
    
    for letter in text:
        reversed_text = letter + reversed_text
    
    print(reversed_text)

# Call the function
reverse_text()

### Exercise 5

Code from lecture 1.2 and 2.1

In [ ]:
# Define the function
def find_min_max(numbers):
    min_value = None
    max_value = None

    for number in numbers:
        if min_value is None or number < min_value:
            min_value = number

        if max_value is None or number > max_value:
            max_value = number

    return min_value, max_value


# Pass one collection as a single argument
values = [4, 9, 1, 7, 3]

# Unpack the returned values
min_value, max_value = find_min_max(values)

# Print the results
print(f"Min value is: {min_value}")
print(f"Max value is: {max_value}")

### Exercise 6

Code from lecture 1.2 and 2.1

In [ ]:
import random

# Choose a random number between 1 and 10
secret_number = random.randint(1, 10)

# Ask the user to guess the number
guess = int(input("Guess the number between 1 and 10: "))

# Keep asking until the guess is correct
while guess != secret_number:
    if guess > secret_number:
        print("Too high! Try again.")
    else:
        print("Too low! Try again.")

    guess = int(input("Guess the number between 1 and 10: "))

# Print success message
print("You guessed the right number.")

### Exercise 7

In [ ]:
# Set the correct password
correct_password = "password"

# Keep asking until the correct password is entered
while True:
    password = input("Enter the password: ")

    if password == correct_password:
        print("Access Granted!")
        break
    else:
        print("Incorrect password. Try again.")

### Exercise 8

Code from lecture 1.2 and 2.1

In [ ]:
import math

def series(x, n):
    s = 0

    for i in range(1, n + 1):
        s = s + x * (5 ** i) ** 2 / (i + math.factorial(i + 1))

    return s

x = float(input("Enter x: "))
n = int(input("Enter N: "))

answer = series(x, n)
print(answer)

### Exercise 9

Code from lecture 2.2 , 3.1 and https://www.slingacademy.com/article/how-to-use-numpy-for-basic-image-manipulation/
for fliping the image

pip install numpy

In [ ]:
import numpy as np
import matplotlib.pyplot as plt  # displaying images
import PIL  # Python Imaging Library - image editing
import urllib  # Library handling URLs (like requesting)

In [ ]:
image_url = "https://thumbs.dreamstime.com/b/ocean-sunset-landscape-bird-high-resolution-image-flying-towards-colorful-romantic-sky-246711534.jpg"

In [ ]:
image_data = urllib.request.urlopen(image_url)
image = PIL.Image.open(image_data)
np_image = np.array(image)

horizontal = np.flip(np_image, axis=1)
vertical = np.flip(np_image, axis=0)

plt.imshow(horizontal)
plt.show()

plt.imshow(vertical)
plt.show()

### Exercise 10

Code from lecture 2.2 and 3.1

In [ ]:
import numpy as np

In [ ]:
# 1) Create a NumPy array
temperatures = np.array([22, 24, 19, 21, 23, 25, 26, 27, 24, 23,
                         20, 22, 21, 19, 18, 22, 23, 24, 26, 28,
                         30, 27, 25, 26, 24, 22, 21, 20, 19, 23])

In [ ]:
# 2) Find minimum, maximum, and average temperature
print(f"Minimum temperature is: {temperatures.min()}")
print(f"Maximum temperature is: {temperatures.max()}")
print(f"Average temperature is: {temperatures.mean()}")

In [ ]:
# 3) Convert Celsius to Fahrenheit
fahrenheit = temperatures * 9 / 5 + 32
print("Temperatures in Fahrenheit are:")
print(fahrenheit)

In [ ]:
# 4) Find all days where temperature was above 25°C
days_above_25 = np.where(temperatures > 25)[0] + 1
print("Days with temperature above 25°C are:")
print(days_above_25)

In [ ]:
# 5) Count how many days had temperature below 20°C
count_below_20 = np.sum(temperatures < 20)
print(f"Number of days below 20°C is: {count_below_20}")

In [ ]:
# 6) Sort temperatures in ascending order
sorted_temperatures = np.sort(temperatures)
print("Sorted temperatures are:")
print(sorted_temperatures)

In [ ]:
# 7) Reshape into 5x6 array
weeks = temperatures.reshape(5, 6)
print("5x6 reshaped array is:")
print(weeks)

### Exercise 11

Code from lecture 3.2 and 4.1

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
np.random.seed(42)

df = pd.DataFrame(np.random.randn(5, 4),
                  index=['A', 'B', 'C', 'D', 'E'],
                  columns=['Col1', 'Col2', 'Col3', 'Col4'])

In [ ]:
print(df)

In [ ]:
print(df.shape)

In [ ]:
print(df.describe())

### Exercise 12

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# Load Iris dataset from Seaborn
df = sns.load_dataset("iris")

# Select numerical columns
numeric_columns = ["sepal_length", "sepal_width", "petal_length", "petal_width"]

# Generate a boxplot for each numerical column
for column in numeric_columns:
    plt.figure(figsize=(8, 5))
    plt.boxplot(df[column])
    plt.title(f"Boxplot of {column}")
    plt.ylabel(column)
    plt.show()

### Exercise 13

In [ ]:
import seaborn as sns
import plotly.express as px

In [ ]:
df = sns.load_dataset('tips')
df = df.groupby(['sex', 'day', 'time'])['tip'].sum().reset_index()

fig = px.sunburst(df, path=['sex', 'day', 'time'], values='tip')
fig.show()

### Exercise 14

pip install scikit-learn

In [ ]:
import seaborn as sns
import pandas as pd
from sklearn.linear_model import LinearRegression

In [ ]:
df = sns.load_dataset('tips')

X = df[['total_bill']]
y = df['tip']

model = LinearRegression()
model.fit(X, y)

new_bill = pd.DataFrame({'total_bill': [10]})
prediction = model.predict(new_bill)

print(f"Predicted tip for bill 10 is: {prediction[0]}")

### Exercise 15

In [41]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.tree import plot_tree, export_text
import pickle
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import itertools

In [42]:
# Load Titanic dataset
dataset_path = 'https://raw.githubusercontent.com/Koldim2001/test_api/refs/heads/main/titanic.csv'
df = pd.read_csv(dataset_path)

In [43]:
# Select features
df = df[['Survived', 'Pclass', 'Age', 'Fare', 'SibSp', 'Parch', 'Sex', 'Embarked']]

In [44]:
df.head()

   Survived  Pclass   Age     Fare  SibSp  Parch     Sex Embarked
0         0       3  22.0   7.2500      1      0    male        S
1         1       1  38.0  71.2833      1      0  female        C
2         1       3  26.0   7.9250      0      0  female        S
3         1       1  35.0  53.1000      1      0  female        S
4         0       3  35.0   8.0500      0      0    male        S

In [45]:
# Data cleaning
df = df.dropna(subset=['Age', 'Embarked'])

In [46]:
df.head()

   Survived  Pclass   Age     Fare  SibSp  Parch     Sex Embarked
0         0       3  22.0   7.2500      1      0    male        S
1         1       1  38.0  71.2833      1      0  female        C
2         1       3  26.0   7.9250      0      0  female        S
3         1       1  35.0  53.1000      1      0  female        S
4         0       3  35.0   8.0500      0      0    male        S

In [ ]:
# One-hot encode Sex
enc_sex = preprocessing.OneHotEncoder()
enc_sex.fit(df[['Sex']])
sex_one_hot = enc_sex.transform(df[['Sex']]).toarray()
df[['female', 'male']] = sex_one_hot

In [ ]:
# One-hot encode Embarked
enc_embarked = preprocessing.OneHotEncoder()
enc_embarked.fit(df[['Embarked']])
embarked_one_hot = enc_embarked.transform(df[['Embarked']]).toarray()
df[['C', 'Q', 'S']] = embarked_one_hot

In [ ]:
# Create inputs and targets
input_cols = ['Pclass', 'Age', 'Fare', 'SibSp', 'Parch', 'female', 'male', 'C', 'Q', 'S']
inputs, targets = df[input_cols], df['Survived']

In [ ]:
# Split dataset
inputs_train, inputs_test, targets_train, targets_test = train_test_split(
    inputs, targets, test_size=0.2, random_state=42)

In [ ]:
# Build and train model
model = DecisionTreeClassifier(max_depth=5, min_samples_split=10, random_state=42)
model.fit(inputs_train, targets_train)

In [ ]:
# Calculate updated accuracy
predictions_test = model.predict(inputs_test)
acc = accuracy_score(targets_test, predictions_test)
print("Updated accuracy:", acc)

In [ ]:
# Prediction for a single person
single_person = pd.DataFrame({
    'Pclass': [3],
    'Age': [30],
    'Fare': [15.0],
    'SibSp': [0],
    'Parch': [0],
    'female': [0],
    'male': [1],
    'C': [0],
    'Q': [0],
    'S': [1]
})

single_prediction = model.predict(single_person)
print("Prediction for a single person:", single_prediction[0])

In [ ]:
# Feature importance
importance_df = pd.DataFrame({
    'feature': input_cols,
    'importance': model.feature_importances_
}).sort_values('importance', ascending=False)

plt.title('Feature Importance')
sns.barplot(data=importance_df, x='importance', y='feature', hue='importance', legend=False)
plt.show()